name: Train Azure Machine Learning Jobs

on:
  workflow_dispatch:  # Manual trigger

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install Azure ML extension
        run: az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Trigger Azure ML experiment job
        run: |
          az ml job create --file src/job.yml \
            --set inputs.training_data=azureml:diabetes-dev-folder:2 \
            --set experiment_name=diabetes-data-example-dev \
            --resource-group azure-ml-rg \
            --workspace-name azure-ml \
            --stream

  production:
    runs-on: ubuntu-latest
    needs: experiment  # Ensures production runs only if experiment is successful
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install Azure ML extension
        run: az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Trigger Azure ML production job
        run: |
          az ml job create --file src/job.yml \
            --set inputs.training_data=azureml:diabetes-prod-folder:1 \
            --set experiment_name=diabetes-data-example-prod \
            --resource-group azure-ml-rg \
            --workspace-name azure-ml \
            --stream
