name: CI Workflow

on:
  pull_request:
    branches:
      - main  # Adjust the branch as needed

jobs:
  lint:
    name: Run Flake8 Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
            python -m pip install flake8
      - name: Run Flake8
        run: flake8 src/model/

  test:
    name: Run Pytest Unit Tests
    runs-on: ubuntu-latest
    needs: lint  # Ensures linting runs before tests
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest tests/  # Run all test files inside the 'tests' folder
